name: lint

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'
      - 'pyproject.toml'

jobs:
  lint:
    name: Check code style

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install poetry

      - run: poetry install

      - run: poetry show

      - run: |
          poetry run autoflake --in-place --remove-unused-variables -r src/ tests/ --check; \
          poetry run black src/ tests/ --check; \
          poetry run isort src/ tests/ --check;
