name: Lint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install poetry

      - run: poetry install

      - run: poetry show

      - name: autoflake, black, isort
        run: |
          poetry run autoflake --in-place --remove-unused-variables -r src/ tests/ --check; \
          poetry run black src/ tests/ --check; \
          poetry run isort src/ tests/ --check;
