name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  pytest:
    strategy:
      matrix:
        python: ['3.11', '3.12', '3.13']
        os: ['ubuntu-latest', 'windows-latest']

    name: Python ${{ matrix.python }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - run: pip install poetry

      - run: poetry install

      - run: poetry show

      - run: poetry run pytest
